version: "3.9"

services:
  julia-backend:
    build:
      context: ./hrm_julia_backend
      dockerfile: Dockerfile
    environment:
      JULIA_HOST: "0.0.0.0"
      JULIA_PORT: "${JULIA_PORT:-9000}"
      JULIA_NUM_THREADS: "${JULIA_THREADS:-auto}"
    ports:
      - "9000:9000"
    volumes:
      - ./:/workspace:ro
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:9000/healthz" ]
      interval: 5s
      timeout: 2s
      retries: 30
    restart: unless-stopped

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.Dockerfile
    depends_on:
      julia-backend:
        condition: service_healthy
    environment:
      PLAN_PATH: "${PLAN_PATH:-/workspace/plan.json}"
      ORCH_LOG_LEVEL: "${ORCH_LOG_LEVEL:-INFO}"
      JULIA_URL: "http://julia-backend:9000"
    command: [ "python", "-u", "matrix_orchestrator.py", "--plan", "/workspace/plan.json" ]
    volumes:
      - ./:/workspace
    working_dir: /workspace
    restart: on-failure

  ruby-bridge:
    image: ruby:3.3-slim
    working_dir: /workspace
    command: [ "ruby", "bridge.rb" ]
    volumes:
      - ./:/workspace
    depends_on:
      julia-backend:
        condition: service_healthy
