
image: python:3.11
stages: [lint, test, publish]

cache:
  key: "pip"
  paths: [ ".cache/pip" ]

lint:
  stage: lint
  script:
    - pip install ruff
    - ruff check .

test:
  stage: test
  script:
    - pip install -e .[test]
    - pytest -q --maxfail=1

publish:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - pip install build twine
    - python -m build
    - twine upload -u __token__ -p $PYPI_TOKEN dist/*
